# Generated by Django 6.0.3 on 2026-03-29 05:46

import uuid
import django.db.models.deletion
from django.db import migrations, models


def populate_share_slugs(apps, schema_editor):
    Trip = apps.get_model('itinerary', 'Trip')
    for trip in Trip.objects.filter(share_slug=''):
        trip.share_slug = uuid.uuid4().hex[:16]
        trip.save(update_fields=['share_slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0002_trip_booking_reference_trip_is_booked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='currency',
            field=models.CharField(choices=[('INR', '₹ INR'), ('USD', '$ USD'), ('EUR', '€ EUR'), ('GBP', '£ GBP'), ('JPY', '¥ JPY'), ('AUD', 'A$ AUD'), ('CAD', 'C$ CAD'), ('SGD', 'S$ SGD')], default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='trip',
            name='dest_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='dest_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        # Add share_slug without unique constraint first, then populate, then add unique
        migrations.AddField(
            model_name='trip',
            name='share_slug',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.RunPython(populate_share_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='trip',
            name='share_slug',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='weather_forecast',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='TripInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='itinerary.trip')),
            ],
        ),
    ]

