# Generated by Django 5.2.8 on 2026-03-29 05:43

import secrets
from django.db import migrations, models


def populate_share_slugs(apps, schema_editor):
    Trip = apps.get_model('itinerary', 'Trip')
    for trip in Trip.objects.filter(share_slug=''):
        trip.share_slug = secrets.token_urlsafe(24)
        trip.save(update_fields=['share_slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0002_trip_booking_reference_trip_is_booked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='currency',
            field=models.CharField(choices=[('INR', '₹ INR'), ('USD', '$ USD'), ('EUR', '€ EUR'), ('GBP', '£ GBP'), ('JPY', '¥ JPY'), ('AUD', 'A$ AUD'), ('CAD', 'C$ CAD'), ('SGD', 'S$ SGD')], default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='trip',
            name='dest_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='dest_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        # Add share_slug without unique constraint first, populate, then add constraint
        migrations.AddField(
            model_name='trip',
            name='share_slug',
            field=models.CharField(blank=True, max_length=40, default=''),
            preserve_default=False,
        ),
        migrations.RunPython(populate_share_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='trip',
            name='share_slug',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
    ]
